### PR TITLE
show events on every day which are in the timeinterval between start …

### PR DESCRIPTION
**Pull request by P1tt187**
…and stop
grafik

### CODE REVIEW

**Comment by P1tt187** [comment]
but thats correct, because ists ending at the next day, so the event is on both days.
how can we detect, if an event have to be shown on both days or not?

**Comment by 4D44H** [comment]
Might be technically correct, but makes no sense - we don't need a single-day event shown on the next day just because it ends after midnight 😉  
One solution would be to do the same as in the month view earlier - offset the date by 5 hours (or so). This way you count the day as "ended" on 5 AM next day, which should take care of most of the cases (open till 01:00, 02:00, 03:00, etc).

**Comment by bedo2991** [comment]
Stage one: set a time between 5 am and 8 am as "date changing time" for all section.
Stage 2: allow each section to define when the working day ends.

**Comment by 4D44H** [comment]
Another solution could be to check if the event **duration** is bigger than 24 hours. 
Yet I'm not sure if that's better then a simple offset of a day's ending time.

**Comment by bedo2991** [comment]
I would also make the "continue" events sleeker than the main one (the starting and DV time are anyway useless there).
image

**Comment by P1tt187** [comment]
@bedo2991 looks like a cool enchancement, but if have no idea how to implement it

**Comment by P1tt187** [comment]
@4D44H should be fixed now

**Comment by 4D44H** [comment]
Yeah, this looks better, thanks!

While we are at it: I am trying to figure out how the events sorted inside the view. It's not be time_start now, so what decides the order?

image

**Comment by 4D44H** [comment]
The question would be also: how _should_ it be sorted?
- The "calendar-approach" would dictate "by time_start", so we'd get an ordered schedule of events.
- The "list-approach" could by "by section", so we'd get an overview who has what at this day that's easier to read if you check multiple sections, but is useless if you only select one.
- The IMHO best way would be actually both: sort by section, **then** by time_start, and multi-day events get sent to the top because they began a day or two earlier.

Thoughts?

**Comment by 4D44H** [comment]
(Example: on a screenshot above on wednesday, the red "Mittwochsöffnung" begins at 10:04 before "test 19-22" at 10:47, so it should be above it)

**Comment by bedo2991** [comment]
I would still follow the calendar approach independently from the section. It's more "democratic" and doesn't depend on the section id/name.

**Comment by 4D44H** [comment]
Oooor.... and you might hate me for this, but.... make it a filter button? 🙈 🙈 🙈 
_* ducks and runs away *_

**Comment by bedo2991** [comment]
Now that you talk about it, we'll need a filter button for the multiday events probably...

**Comment by P1tt187** [comment]
basicly its sorted by section->title, maybe it should be time and section->title

**Comment by 4D44H** [comment]
MonthController@showMonth line 83++:
```
$events = ClubEvent::where('evnt_date_start', '>=', $firstDay->format("Y-m-d"))
            ->where('evnt_date_start', '<=', $lastDay->format("Y-m-d"))
            ->orderBy('evnt_date_start')
            ->orderBy('evnt_time_start')
            ->with('showToSection')
            ->with('shifts')
            ->with('section')
            ->get(); 
```

So the events already _are_ sorted by time, it's just that something is "unsorting" them afterwards 🙈 

Removing "->sortBy('section.title') " from monthCell line 50:
```
@foreach($events->sortBy('section.title') as $clubEvent)
```
Only fixes it partially, there still are some events in the wrong order. Couldn't really find the reason why.

**Comment by P1tt187** [comment]
or more simple: $events->sortBy('evnt_time_start,section.title')

**Comment by 4D44H** [comment]
image

Unfortunately, some events are still not sorted, see attached.

As an example for monday events:
*A*
image

*B*
image

*B* on 17.09.2018 at 11:40 should be above *A* starting on 17.09.2018 at 13:14

**Pull request merged**
