### PR TITLE
Month view - Day restyling

### PR DESCRIPTION
**Pull request by bedo2991**
Cell widht: the whole day cell - padding
**Guests:**
First row: Icon + Starting Time
Second row: Event name

**Logged in users:**
First row: Icon Starting time (DV time)
Second row: Event name
image

### CODE REVIEW

**Comment by 4D44H** [comment]
Looks very good! 👍
But let's adjust the DV time: no it's not clear what the second time means.
Can you do "21:00 (DV: 20:00)"?

**Comment by 4D44H** [comment]
Otherwise this is exactly what I had in mind, looks much better now, and less event titles will be cut off!

**Comment by 4D44H** [comment]
"prep"?🙃

**Comment by bedo2991** [comment]
image
I think it looks better without it and that logged in people will understand what it means after 10 seconds, but if you like it with it...

**Comment by 4D44H** [comment]
I like it more with description. But let's see what the others think :)

**Comment by bedo2991** [comment]
Improved Word Wrapping:
image

**Comment by ThomDietrich** [comment]
How about no additional "DV/Prep" but a tooltip for the second time?

**Pull request merged**
