### PR TITLE
Feature/generic section colors

### PR DESCRIPTION
**Pull request by 4D44H**
Event colors are now pulled out of palette.css using values saved in the Section model.

### CODE REVIEW

**Comment by 4D44H** [comment]
For the record: I'm working in parallel on a big month view redesign, and basically rewrite it from scratch, so the aim of these changes are _only_ to introduce correct color handling. No further refactoring was intended (or should be done at this point) - it will be done later in a separate PR.

**Comment by 4D44H** [comment]
[[2] (ILSC) Rethink events color concept for different sections](https://trello.com/c/Brf0VFxb/301-2-ilsc-rethink-events-color-concept-for-different-sections)

**Comment by P1tt187** [comment]
after switching to the branch all events are not styled until i choose a color in the section menu
could you please add a migration with default colors for each section?

**Comment by 4D44H** [comment]
It's rather a seeds problem - the seeder has not added these values. in prod they are already set, afaik.

**Comment by 4D44H** [comment]
That should do it, try `php artisan migrate:refresh --seed`

**Comment by P1tt187** [comment]
I testet with the dump, so this is missing for those data

**Comment by 4D44H** [comment]
Hm, okay... I thought we did that already. I'll add it later then, together with other section preferences like DV times etc.

**Comment by stefanheyder** [comment]
Just one comment: I'd rather have the palette.css installed in node_modules so we can easily update that dependency. https://trello.com/c/GpmoQsFy/404-1-move-google-color-palette-to-npm

**Pull request closed without merging**
