### PR TITLE
Feature/refactor shift management

### PR DESCRIPTION
**Pull request by P1tt187**

### CODE REVIEW

**Comment by P1tt187** [comment]
[[2] integrate Templates in shiftType Management and refactor it](https://trello.com/c/dJqGgn7S/449-2-integrate-templates-in-shifttype-management-and-refactor-it)

**Comment by stefanheyder** [comment]
Very nice! There is only one thing I have to remark: you don't see the use of shifts in templates of other sections if you are only CL (which is fine). The problem that arises, is that if you replace all shifts in the templates of your section but not the other section you can't delete the shifttype (because it is still in use), but you don't see why (because you have no information about its use in other sections). 

Possible solution for this: Also show those templates in the overview, but indicate that you can't modify them (if you are CL).

**Comment by P1tt187** [comment]
good point, i will try to implement that

**Comment by stefanheyder** [comment]
Otherwise I got no objections to merging this PR.

**Comment by P1tt187** [comment]
is this better?

**Comment by stefanheyder** [comment]
Thank you, will merge this PR now.

**Pull request merged**
