### PR TITLE
log messages are caused by a select that gives duplicated results, ma…

### PR DESCRIPTION
**Pull request by P1tt187**
…ke it unique will fix the problem

### CODE REVIEW

**Comment by stefanheyder** [comment]
Why not add a `->distinct()` to the `User::roles()` query? This way, one does not have to remember that you have to call `unique()` on the roles collection.

**Comment by P1tt187** [comment]
`distinct` is evil
its very bad for database performance, calling `unique `on the result is cheaper
its better to avoid `distinct `no matter what sql dialect you use

https://webbtechsolutions.com/2009/07/24/the-effects-of-distinct-in-a-sql-query/
https://stackoverflow.com/questions/5341276/sql-distinct-keyword-bogs-down-performance

**Comment by stefanheyder** [comment]
But with this solution one has to remember to call `->unique()` on the result if one were to iterate over the roles of a user, which is also bad.

Is there a reason why the results are not distinct? Maybe we can fix that instead of using DISTINCT.

**Comment by P1tt187** [comment]
yeah, this is just a quickfix
i think the main cause is in the mapping of the user and the role class
the generated sql is the main cause

**Comment by stefanheyder** [comment]
I have created a ticket for this, see https://trello.com/c/BeOsc9A8/506-2-fix-issues-with-roles-method-on-users-class.

In this case I have no objections to merging.

**Pull request merged**
